name: send-cat-daily

on:
  schedule:
    - cron: "00 10 * * *"
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix=${{ secrets.TOKENS }}" >> $GITHUB_OUTPUT && \
          echo "${{ fromJson(secrets.TOKENS) }}"
  send-message:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        token: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    steps:
      - name: query
        id: query
        env:
          Url: "https://catasaservice.xyz/api/random"
        run: |
          json=$(curl https://catasaservice.xyz/api/random) && \
          Fullsize=$(echo $json | jq .data.photos[0].full) && \
          Thumbnail=$(echo $json | jq .data.photos[0].medium) && \
          echo "Fullsize=$Fullsize" >> $GITHUB_OUTPUT && \
          echo "Thumbnail=$Thumbnail" >> $GITHUB_OUTPUT

      - name: send
        if: success()
        env:
          Message: "UwU"
          Target: https://notify-api.line.me/api/notify
          Fullsize: ${{ steps.query.outputs.Fullsize }}
          Thumbnail: ${{ steps.query.outputs.Thumbnail }}
        run: |
          curl -H 'Authorization: Bearer ${{ matrix.token }}' \
          -F "message=$Message" \
          -F "imageFullsize=$Fullsize" \
          -F "imageThumbnail=$Thumbnail" \
          $Target
