name: send-get-off-work-daily

on:
  workflow_dispatch:
  
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: query
        env:
          Url: "https://catasaservice.xyz/api/random"
        run: |
          json=$(curl https://catasaservice.xyz/api/random) && \
          Fullsize=$($json | jq .data.photos[0].full) && \
          Thumbnail=$($json | jq .data.photos[0].medium)

      - name: send
        env:
          Message: "UwU"
          Target: https://notify-api.line.me/api/notify
        run: |
          curl -H 'Authorization: Bearer ${{ secrets.GROUP_TOKEN_1 }}' \
          -F "message=$Message" \
          -F "imageFullsize=$Fullsize" \
          -F "imageThumbnail=$Thumbnail" \
          $Target
